@startuml
' 1st level calls
class populateEntities

populateEntities --> handleExecutionTime
populateEntities --> _loadErrorConfig
populateEntities --> validateSheetRecord
populateEntities --> normalizeValues
populateEntities --> splitValuesForEntity
populateEntities --> loadEntities
populateEntities --> saveEntities
populateEntities --> handlePopulationError

' 2nd level calls
validateSheetRecord --> handleValidationError

splitValuesForEntity --> loadFieldValue
splitValuesForEntity --> concat

loadEntityDefaultValues --> getDefault

loadEntities --> instantiateEntities

saveEntities --> registerConflictingRow
saveEntities --> notify

handlePopulationError --> handleError

' 3rd level calls
loadFieldValue --> getDefault
loadFieldValue --> getTransformation

handleValidationError --> handleError
handleValidationError --> writeError 


@enduml
