@startuml

ImportService -> EntityPopulator : populateEntities()
EntityPopulator -> PhpConfigsHelper : handleExecutionTime()
EntityPopulator -> ValidationHelper : loadErrorConfig()
EntityPopulator -> EntityPopulator : traverseSheet()
activate EntityPopulator
EntityPopulator ->  SheetRecordParserAbstract : getSheetRecordDefinition()
note right
    recordDefinition is used through all the process to relate entities and calculate defaults
    it gets loaded from config.yml  
end note

loop for each sheet record
    EntityPopulator -> EntityPopulator : sanitizeSheetRecord()
    activate EntityPopulator
        EntityPopulator -> RecordSanitizerHelper : normalizeValues() 
        EntityPopulator -> RecordSanitizerHelper : valueArrayChunkForEntitiesPerRecord() 
        EntityPopulator -> RecordSanitizerHelper : loadRecordDefinitionDefaultValuesPerEntityArrayChunk() 
    deactivate EntityPopulator
 
    alt try
        EntityPopulator -> EntityFactoryHelper : getRecordEntitiesInstances()
        note right
            Each Recod could define several Entities and distribute its data among them
        end note

        EntityPopulator -> EntityRelationsHelper : relateEntities()
        EntityPopulator -> EntityPersistenceHelper : saveEntities()
    else catch Boom
        EntityPopulator -> ValidationHelper : handlePopulationError()
    end

end
deactivate EntityPopulator
EntityPopulator -> ValidationHelper : getErrors()
EntityPopulator --> ImportService : errors

@enduml
